### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by sivaraj-v** [MichaelCurrin/react-ssr-quickstart#1]
```
Warning: Did not expect server HTML to contain the text node "
        " in <div>.
    at h1
```

**Comment by MichaelCurrin** [comment]
Can you add a screenshot? Is this the client getting bad content from server?

**Comment by MichaelCurrin** [comment]
Oh I found the issue on the frontend.

I fixed with by taking out whitespace around `${component}` in the server.js HTML.
